# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "aws-s3-cse"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Nijmeijer"]
  s.date = "2012-04-27"
  s.description = "Provides a ruby implementation of the Client Side Encryption client for AWS-S3"
  s.email = "tom@nijmeijer.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "aws-s3-cse.gemspec",
    "lib/aws-s3-cse.rb",
    "lib/aws/s3/crypter.rb",
    "lib/aws/s3/encrypted_client.rb",
    "lib/aws/s3/encrypted_config.rb",
    "lib/aws/s3/encryption_errors.rb",
    "lib/aws/s3/model.rb",
    "spec/aws/s3/crypter_spec.rb",
    "spec/aws/s3/encrypted_client_spec.rb",
    "spec/aws/s3/model_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tcnijmeijer/aws-s3-cse"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Provides a ruby implementation of the Client Side Encryption client for AWS-S3"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-sdk>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rspec-mocks>, [">= 2.9.0"])
      s.add_development_dependency(%q<rspec-spies>, [">= 2.1.0"])
      s.add_development_dependency(%q<rcov>, ["= 0.9.9"])
    else
      s.add_dependency(%q<aws-sdk>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rspec-mocks>, [">= 2.9.0"])
      s.add_dependency(%q<rspec-spies>, [">= 2.1.0"])
      s.add_dependency(%q<rcov>, ["= 0.9.9"])
    end
  else
    s.add_dependency(%q<aws-sdk>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rspec-mocks>, [">= 2.9.0"])
    s.add_dependency(%q<rspec-spies>, [">= 2.1.0"])
    s.add_dependency(%q<rcov>, ["= 0.9.9"])
  end
end

